version: '3.8'

services:
  github-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-api
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    networks:
      - github-api-network

  # Servicio para desarrollo
  github-api-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: github-api-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev
    restart: unless-stopped
    networks:
      - github-api-network

networks:
  github-api-network:
    driver: bridge